import { z } from "zod";
import { MAX_MAJOR_AMOUNT, normalizeCurrency } from "./money";

// ============================================================================
// 1. CREATE PAYMENT — what SACCO/Church send TO the Payment Service
//
// This is the boundary that matters most. Validate this BEFORE touching the
// database. If validation fails here, you never even create a row, which
// keeps payment_intents free of garbage data from a malformed request.
// ============================================================================

export const CreatePaymentRequestSchema = z.object({
  // Which app is asking. Resolved against the `applications` table -
  // if it doesn't match an active row there, reject with 400, not 500.
  applicationCode: z.string().min(1),

  // Optional: which tenant within that app. Omit for single-tenant apps.
  tenantCode: z.string().min(1).optional(),

  // Which kind of payment this is (deposit, loan_repayment, tithe...).
  // Resolved against `payment_types` scoped to applicationCode.
  paymentTypeCode: z.string().min(1),

  // The member/invoice/whatever id from the SOURCE app's world.
  // Payment Service stores this opaquely - never validates its shape.
  externalEntityId: z.string().min(1),

  // Money. Reject non-positive amounts here rather than relying solely on
  // the DB check constraint - better to fail with a clear 400 message than
  // a raw Postgres constraint error.
  // Upper-bounded, not just positive: the column is Decimal(14,2), so an
  // out-of-range amount reaches Postgres as a numeric overflow and comes back
  // as a 500 instead of a validation error.
  amount: z.number().finite().positive().max(MAX_MAJOR_AMOUNT),
  // Normalised to upper case at the boundary. Currency is part of the wallet
  // key, so "ugx" and "UGX" would otherwise create two wallets for one currency
  // and split the tenant's balance between them.
  currency: z
    .string()
    .trim()
    .regex(/^[A-Za-z]{3}$/, "must be a three-letter ISO 4217 currency code")
    .default("UGX")
    .transform(normalizeCurrency),

  // Loose validation here (provider-specific formatting happens in the
  // gateway adapter, not at this boundary).
  phoneNumber: z.string().min(9).max(15),

  // Generated by the CALLING app, once per attempt. This is what makes
  // the endpoint safe to retry - same key in twice returns the same
  // intent instead of creating a duplicate.
  idempotencyKey: z.string().min(8),

  // Optional: which provider should take this payment ("livepay").
  //
  // Providers with no working adapter are rejected with a 400 and the list of
  // usable ones. Without this field the caller had no way to influence
  // routing at all, and selection fell back to an unordered query that could
  // pick a provider incapable of taking the payment.
  providerCode: z.string().min(1).max(32).optional(),

  // Opaque passthrough. Payment Service never reads these keys, just
  // stores and echoes them back in the completion notification.
  metadata: z.record(z.string(), z.unknown()).optional().default({}),
});

export type CreatePaymentRequest = z.infer<typeof CreatePaymentRequestSchema>;

// What the Payment Service sends back immediately after creating the intent.
// Note: status here is whatever it is right after creation (usually
// "pending" or "processing") - NOT the final result. The final result
// arrives later via the internal notification below.
export const CreatePaymentResponseSchema = z.object({
  paymentId: z.string().uuid(),
  reference: z.string(),
  status: z.enum(["pending", "processing", "success", "failed", "expired", "cancelled"]),
});

export type CreatePaymentResponse = z.infer<typeof CreatePaymentResponseSchema>;

// ============================================================================
// 2. PROVIDER WEBHOOK — what LivePay (or Relworx, etc.) sends INTO the
// Payment Service. Kept generic here; if LivePay's actual payload shape
// differs, narrow this down once you see a real example in their docs.
//
// IMPORTANT: this schema validates SHAPE only. Signature verification is a
// separate step that must happen first, using the raw request body
// (verify against the raw bytes, not the parsed/re-serialized JSON, since
// re-serialization can change byte-for-byte content and break HMAC checks).
// ============================================================================

export const ProviderWebhookPayloadSchema = z.object({
  transactionId: z.string().min(1),
  reference: z.string().min(1).optional(), // your own reference, if the
                                           // provider echoes it back
  amount: z.number().finite().positive().max(MAX_MAJOR_AMOUNT),
  currency: z.string().trim().regex(/^[A-Za-z]{3}$/).optional().transform((c) => (c ? normalizeCurrency(c) : c)),
  status: z.string().min(1), // kept as raw string here - map to your
                               // internal PaymentStatus enum in code,
                               // don't trust the provider's vocabulary
                               // to match yours exactly
});

export type ProviderWebhookPayload = z.infer<typeof ProviderWebhookPayloadSchema>;

// ============================================================================
// 3. INTERNAL NOTIFICATION — what the Payment Service sends TO the SACCO/Church
// app when a payment reaches a terminal state (success/failed/expired/cancelled).
// Deliberately excludes non-terminal statuses (pending/processing) because
// there's nothing the app needs to do for those.
// ============================================================================

export const InternalNotificationPayloadSchema = z.object({
  paymentIntentId: z.string().uuid(),
  reference: z.string(),
  status: z.enum(["success", "failed", "expired", "cancelled"]),
  amount: z.number().positive(),
  currency: z.string().length(3),
  externalEntityId: z.string().nullable(),
  metadata: z.record(z.string(), z.unknown()),
  providerPaymentId: z.string().nullable(),
  failureReason: z.string().nullable(),
});

export type InternalNotificationPayload = z.infer<typeof InternalNotificationPayloadSchema>;