import type { Metadata, Viewport } from "next";
// Self-hosted Geist (from the `geist` npm package) instead of `next/font/google`.
//
// `next/font/google` downloads the font files from fonts.googleapis.com at
// BUILD time. That made every production build depend on Google's CDN being
// reachable: any network hiccup, proxy, or air-gapped CI runner failed the
// entire build with "Failed to fetch `Geist` from Google Fonts".
//
// The npm package ships the identical variable font files and exposes the same
// CSS variables (--font-geist-sans / --font-geist-mono) that globals.css and
// tailwind.config.ts already reference, so the typography is unchanged.
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { PwaRegistrar } from "@/components/pwa-registrar";

const geistSans = GeistSans;
const geistMono = GeistMono;

export const viewport: Viewport = {
  themeColor: "#09090b",
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  viewportFit: "cover",
};

export const metadata: Metadata = {
  title: "Na'jiki Tech — Payment & Messaging Dashboard",
  description: "Unified payment and messaging gateway for SACCO, Church, and School platforms. Track revenue, transactions, and webhooks across all applications.",
  // Points at the manifest generated by src/app/manifest.ts (served at
  // /manifest.webmanifest). Next.js does NOT inject this link automatically —
  // verified by removing it and rendering the page, which produced zero
  // rel="manifest" tags — so it must stay here. It previously pointed at the
  // hand-maintained public/manifest.json, which meant the generated manifest was
  // never used and the two copies had already drifted (icon.svg `purpose`).
  manifest: "/manifest.webmanifest",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Na'jiki",
  },
  formatDetection: {
    telephone: false,
  },
  icons: {
    icon: [
      { url: "/icons/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/icon-192x192.png", sizes: "192x192", type: "image/png" },
      { url: "/logo.svg", type: "image/svg+xml" },
    ],
    shortcut: "/icons/icon-192x192.png",
    apple: [
      { url: "/icons/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning data-scroll-behavior="smooth">
      <head>
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="Na'jiki" />
        <link rel="apple-touch-icon" href="/icons/apple-touch-icon.png" />
      </head>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        {/* Instant Brand Splash Screen (0ms initial paint, pure CSS fade-out) */}
        <div
          id="najiki-splash-screen"
          suppressHydrationWarning
          className="splash-bg fixed inset-0 z-[99999] flex flex-col items-center justify-center cursor-pointer select-none"
        >
          <div className="splash-icon">
            <svg viewBox="0 0 100 100" fill="none" xmlns="http://www.w3.org/2000/svg" className="w-full h-full">
              <path
                d="M40 80 V25 C40 15, 60 15, 60 30 C60 45, 40 45, 40 45"
                stroke="oklch(0.72 0.19 155)"
                strokeWidth="4"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </div>
          <h1 className="splash-title">Najiki</h1>
          <p className="splash-tagline">Because every name matters.</p>
        </div>
        {children}
        <Toaster />
        <PwaRegistrar />
      </body>
    </html>
  );
}

